In [65]:
import pandas as pd, json, numpy as np

data = pd.read_csv(
    "2022_results.csv",
    usecols=[i for i in range(2, 10)],
    index_col=["candidateName"]
)
data_maddy = data.iloc[1, -3:]
data = data.groupby("PartyAb").sum().sort_values("first preferences", ascending=False)

sankey_data = {
    "nodes": [],
    "links": []
}
sankey_nocock = {
    "nodes": [],
    "links": []
}
for i, party in enumerate(data.index):
    sankey_data["nodes"].append({
        "node": int(i),
        "name": party,
        "party": party
    })
for i, preference in enumerate(data.columns[1:]):
    sankey_data["nodes"].append({
        "node": int(i + len(data)),
        "name": preference,
        "party": (
            "ALP" if i < 2 else
            "LP" if i == 2 else
            "DAVI" if i == 3 else "exhausted"
        )
    })
for i, party in enumerate(data.index):
    if i == 0:
        sankey_data["links"].append({
            "source": 0,
            "target": int(len(data)),
            "value": data.iat[0, 2]
        })
        # for j in range(3):
        #     maddy_data[j] > 0:
        #         sankey_data["links"].append({
        #             "source": 0,
        #             "target": int(len(data) + j + 1)
        #         })            
    else:
        for j in range(5):
            if data.iat[i, j + 1] > 0:
                sankey_data["links"].append({
                    "source": int(i),
                    "target": int(j + len(data)),
                    "value": data.iat[i, j + 1]
                })
# for i in range(3):
#     if data.iat[0, i + 3] > 0:
#         sankey_data["links"].append({
#             "source": int(len(data)),
#             "target": int(len(data) + i + 1),
#             "value": data_nocock.iat[0, i + 3]
#         })
class NpEncoder(json.JSONEncoder):
    def default(self, obj):
        if isinstance(obj, np.integer):
            return int(obj)
        if isinstance(obj, np.floating):
            return float(obj)
        if isinstance(obj, np.ndarray):
            return obj.tolist()
        return super(NpEncoder, self).default(obj)
with open("./sankey_data_2022.json", "w") as file:
    file.write(json.dumps(sankey_data, cls=NpEncoder))
sankey_data

{'nodes': [{'node': 0, 'name': 'ALP', 'party': 'ALP'},
  {'node': 1, 'name': 'LP', 'party': 'LP'},
  {'node': 2, 'name': 'DAVI', 'party': 'DAVI'},
  {'node': 3, 'name': 'GRN', 'party': 'GRN'},
  {'node': 4, 'name': 'KCBR', 'party': 'KCBR'},
  {'node': 5, 'name': 'UAPP', 'party': 'UAPP'},
  {'node': 6, 'name': 'HMP', 'party': 'HMP'},
  {'node': 7, 'name': 'AJP', 'party': 'AJP'},
  {'node': 8, 'name': 'SPP', 'party': 'SPP'},
  {'node': 9, 'name': 'IMO', 'party': 'IMO'},
  {'node': 10, 'name': 'AUP', 'party': 'AUP'},
  {'node': 11, 'name': 'IND', 'party': 'IND'},
  {'node': 12, 'name': 'Gallagher (elected)', 'party': 'ALP'},
  {'node': 13, 'name': 'Gallagher (quota)', 'party': 'ALP'},
  {'node': 14, 'name': 'Seselja', 'party': 'LP'},
  {'node': 15, 'name': 'Pocock', 'party': 'DAVI'},
  {'node': 16, 'name': 'exhausted', 'party': 'exhausted'}],
 'links': [{'source': 0, 'target': 13, 'value': 95074},
  {'source': 1, 'target': 12, 'value': 116},
  {'source': 1, 'target': 14, 'value': 70335.0},
  {'source': 1, 'target': 15, 'value': 283.0},
  {'source': 1, 'target': 16, 'value': 11.0},
  {'source': 2, 'target': 12, 'value': 10},
  {'source': 2, 'target': 14, 'value': 3.0},
  {'source': 2, 'target': 15, 'value': 60289.0},
  {'source': 2, 'target': 16, 'value': 2.0},
  {'source': 3, 'target': 12, 'value': 13790},
  {'source': 3, 'target': 14, 'value': 1161.0},
  {'source': 3, 'target': 15, 'value': 14037.0},
  {'source': 3, 'target': 16, 'value': 391.0},
  {'source': 4, 'target': 12, 'value': 3207},
  {'source': 4, 'target': 14, 'value': 862.0},
  {'source': 4, 'target': 15, 'value': 8390.0},
  {'source': 4, 'target': 16, 'value': 154.0},
  {'source': 5, 'target': 12, 'value': 822},
  {'source': 5, 'target': 14, 'value': 3005.0},
  {'source': 5, 'target': 15, 'value': 1840.0},
  {'source': 5, 'target': 16, 'value': 477.0},
  {'source': 6, 'target': 12, 'value': 1365},
  {'source': 6, 'target': 14, 'value': 849.0},
  {'source': 6, 'target': 15, 'value': 1920.0},
  {'source': 6, 'target': 16, 'value': 416.0},
  {'source': 7, 'target': 12, 'value': 590},
  {'source': 7, 'target': 14, 'value': 297.0},
  {'source': 7, 'target': 15, 'value': 838.0},
  {'source': 7, 'target': 16, 'value': 167.0},
  {'source': 8, 'target': 12, 'value': 466},
  {'source': 8, 'target': 14, 'value': 366.0},
  {'source': 8, 'target': 15, 'value': 713.0},
  {'source': 8, 'target': 16, 'value': 86.0},
  {'source': 9, 'target': 12, 'value': 178},
  {'source': 9, 'target': 14, 'value': 396.0},
  {'source': 9, 'target': 15, 'value': 655.0},
  {'source': 9, 'target': 16, 'value': 229.0},
  {'source': 10, 'target': 12, 'value': 225},
  {'source': 10, 'target': 14, 'value': 61.0},
  {'source': 10, 'target': 15, 'value': 406.0},
  {'source': 10, 'target': 16, 'value': 27.0},
  {'source': 11, 'target': 12, 'value': 240},
  {'source': 11, 'target': 14, 'value': 94.0},
  {'source': 11, 'target': 15, 'value': 192.0},
  {'source': 11, 'target': 16, 'value': 24.0}]}

In [59]:
data

,first preferences,Gallagher (elected),Gallagher (quota),Seselja,Pocock,exhausted
PartyAb,,,,,,
ALP,95232,95107,95074,4156.340608,15721.849289,1288.810104
LP,70745,116,0,70335.000000,283.000000,11.000000
DAVI,60304,10,0,3.000000,60289.000000,2.000000
GRN,29379,13790,0,1161.000000,14037.000000,391.000000
KCBR,12613,3207,0,862.000000,8390.000000,154.000000
UAPP,6144,822,0,3005.000000,1840.000000,477.000000
HMP,4550,1365,0,849.000000,1920.000000,416.000000
AJP,1892,590,0,297.000000,838.000000,167.000000
SPP,1631,466,0,366.000000,713.000000,86.000000
IMO,1458,178,0,396.000000,655.000000,229.000000
AUP,719,225,0,61.000000,406.000000,27.000000
IND,550,240,0,94.000000,192.000000,24.000000

In [62]:
data_maddy

Seselja       23.0
Pocock       100.0
exhausted      2.0
Name: NORTHAM Maddy, dtype: object