In [119]:
import pandas as pd, json, numpy as np

# data = pd.read_csv(
#     "2022_results.csv",
#     usecols=[i for i in range(2, 10)],
#     index_col=["candidateName"]
# )
# data_maddy = data.iloc[1, -3:]
# data = data.groupby("PartyAb").sum().sort_values("first preferences", ascending=False)

# sankey_data = {
#     "nodes": [],
#     "links": []
# }
# for i, party in enumerate(data.index):
#     sankey_data["nodes"].append({
#         "node": int(i),
#         "name": party,
#         "party": party
#     })
# for i, preference in enumerate(data.columns[1:]):
#     sankey_data["nodes"].append({
#         "node": int(i + len(data)),
#         "name": preference,
#         "party": (
#             "ALP" if i < 2 else
#             "LP" if i == 2 else
#             "DAVI" if i == 3 else "exhausted"
#         )
#     })
# for i, party in enumerate(data.index):
#     if i == 0:
#         sankey_data["links"].append({
#             "source": 0,
#             "target": int(len(data)),
#             "value": data.iat[0, 1]
#         })
#         sankey_data["links"].append({
#             "source": int(len(data)),
#             "target": int(len(data) + 1),
#             "value": data.iat[0, 2]
#         })
#         for j in range(3):
#             if data_maddy[j] > 0:
#                 sankey_data["links"].append({
#                     "source": 0,
#                     "target": int(len(data) + j + 1),
#                     "value": data_maddy[j]
#                 })
#             if data.iat[0, j + 3] > 0:
#                 sankey_data["links"].append({
#                     "source": int(len(data)),
#                     "target": int(len(data) + j + 2),
#                     "value": data.iat[0, j + 3]
#                 })
#     else:
#         for j in range(5):
#             if data.iat[i, j + 1] > 0:
#                 sankey_data["links"].append({
#                     "source": int(i),
#                     "target": int(j + len(data)),
#                     "value": data.iat[i, j + 1]
#                 })

data_nocock = pd.read_csv(
    "2022_results_nocock.csv",
    usecols=[i for i in range(2, 9)],
    index_col=["candidateName"]
)
data_nocock = data_nocock.groupby("PartyAb").sum().sort_values("first preferences", ascending=False)

sankey_data_nocock = {
    "nodes": [],
    "links": []
}
for i, party in enumerate(data_nocock.index):
    sankey_data_nocock["nodes"].append({
        "node": int(i),
        "name": party,
        "party": party
    })
for i, preference in enumerate(data_nocock.columns[1:]):
    sankey_data_nocock["nodes"].append({
        "node": int(i + len(data_nocock)),
        "name": preference,
        "party": (
            "ALP" if i == 0 else
            "LP" if i == 1 else
            "GRN" if i == 2 else "exhausted"
        )
    })
for i, party in enumerate(data_nocock.index):
    for j in range(4):
        if data_nocock.iat[i, j + 1] > 0:
            sankey_data_nocock["links"].append({
                "source": int(i),
                "target": int(j + len(data_nocock)),
                "value": data_nocock.iat[i, j + 1]
            })

class NpEncoder(json.JSONEncoder):
    def default(self, obj):
        if isinstance(obj, np.integer):
            return int(obj)
        if isinstance(obj, np.floating):
            return float(obj)
        if isinstance(obj, np.ndarray):
            return obj.tolist()
        return super(NpEncoder, self).default(obj)

# with open("./sankey_data_2022.json", "w") as file:
#     file.write(json.dumps(sankey_data, cls=NpEncoder))
with open("./sankey_data_2022_nocock.json", "w") as file:
    file.write(json.dumps(sankey_data_nocock, cls=NpEncoder))
sankey_data_nocock

{'nodes': [{'node': 0, 'name': 'ALP', 'party': 'ALP'},
  {'node': 1, 'name': 'LP', 'party': 'LP'},
  {'node': 2, 'name': 'GRN', 'party': 'GRN'},
  {'node': 3, 'name': 'KCBR', 'party': 'KCBR'},
  {'node': 4, 'name': 'UAPP', 'party': 'UAPP'},
  {'node': 5, 'name': 'HMP', 'party': 'HMP'},
  {'node': 6, 'name': 'AJP', 'party': 'AJP'},
  {'node': 7, 'name': 'SPP', 'party': 'SPP'},
  {'node': 8, 'name': 'IMO', 'party': 'IMO'},
  {'node': 9, 'name': 'AUP', 'party': 'AUP'},
  {'node': 10, 'name': 'IND', 'party': 'IND'},
  {'node': 11, 'name': 'Gallagher (elected 1st)', 'party': 'ALP'},
  {'node': 12, 'name': 'Seselja (elected 2nd)', 'party': 'LP'},
  {'node': 13, 'name': 'Goreng Goreng', 'party': 'GRN'},
  {'node': 14, 'name': 'exhausted', 'party': 'exhausted'}],
 'links': [{'source': 0, 'target': 11, 'value': 95012},
  {'source': 0, 'target': 12, 'value': 4064.570321540026},
  {'source': 0, 'target': 13, 'value': 14941.553210140608},
  {'source': 0, 'target': 14, 'value': 732.876468319366},
  {'source': 1, 'target': 12, 'value': 77146.0},
  {'source': 1, 'target': 13, 'value': 212.0},
  {'source': 1, 'target': 14, 'value': 91.0},
  {'source': 2, 'target': 12, 'value': 28.0},
  {'source': 2, 'target': 13, 'value': 39173.0},
  {'source': 2, 'target': 14, 'value': 9.0},
  {'source': 3, 'target': 12, 'value': 6361.0},
  {'source': 3, 'target': 13, 'value': 23741.0},
  {'source': 3, 'target': 14, 'value': 1427.0},
  {'source': 4, 'target': 12, 'value': 4497.0},
  {'source': 4, 'target': 13, 'value': 1155.0},
  {'source': 4, 'target': 14, 'value': 1309.0},
  {'source': 5, 'target': 12, 'value': 1995.0},
  {'source': 5, 'target': 13, 'value': 3154.0},
  {'source': 5, 'target': 14, 'value': 1141.0},
  {'source': 6, 'target': 12, 'value': 687.0},
  {'source': 6, 'target': 13, 'value': 1610.0},
  {'source': 6, 'target': 14, 'value': 409.0},
  {'source': 7, 'target': 12, 'value': 830.0},
  {'source': 7, 'target': 13, 'value': 1271.0},
  {'source': 7, 'target': 14, 'value': 315.0},
  {'source': 8, 'target': 12, 'value': 694.0},
  {'source': 8, 'target': 13, 'value': 523.0},
  {'source': 8, 'target': 14, 'value': 594.0},
  {'source': 9, 'target': 12, 'value': 274.0},
  {'source': 9, 'target': 13, 'value': 854.0},
  {'source': 9, 'target': 14, 'value': 123.0},
  {'source': 10, 'target': 12, 'value': 220.0},
  {'source': 10, 'target': 13, 'value': 374.0},
  {'source': 10, 'target': 14, 'value': 64.0}]}

In [118]:
data_nocock["first preferences"].sum()

14255

In [80]:
for i, party in enumerate(data_nocock.index):
    if i == 0:
        sankey_data_nocock["links"].append({
            "source": 0,
            "target": int(len(data_nocock)),
            "value": data.iat[0, 1]
        })
        sankey_data_nocock["links"].append({
            "source": int(len(data_nocock)),
            "target": int(len(data_nocock) + 1),
            "value": data_nocock.iat[0, 2]
        })
        for j in range(3):
            if data_maddy_nocock[j] > 0:
                sankey_data_nocock["links"].append({
                    "source": 0,
                    "target": int(len(data_nocock) + j + 1),
                    "value": data_maddy_nocock[j]
                })
            if data_nocock.iat[0, j + 3] > 0:
                sankey_data_nocock["links"].append({
                    "source": int(len(data_nocock)),
                    "target": int(len(data_nocock) + j + 2),
                    "value": data_nocock.iat[0, j + 3]
                })
    else:
        for j in range(5):
            if data_nocock.iat[i, j + 1] > 0:
                sankey_data_nocock["links"].append({
                    "source": int(i),
                    "target": int(j + len(data_nocock)),
                    "value": data_nocock.iat[i, j + 1]
                })

,first preferences,Gallagher (elected),Gallagher (quota),Seselja,Pocock,exhausted
PartyAb,,,,,,
ALP,95232,95107,95074,4156.340608,15721.849289,1288.810104
LP,70745,116,0,70335.000000,283.000000,11.000000
DAVI,60304,10,0,3.000000,60289.000000,2.000000
GRN,29379,13790,0,1161.000000,14037.000000,391.000000
KCBR,12613,3207,0,862.000000,8390.000000,154.000000
UAPP,6144,822,0,3005.000000,1840.000000,477.000000
HMP,4550,1365,0,849.000000,1920.000000,416.000000
AJP,1892,590,0,297.000000,838.000000,167.000000
SPP,1631,466,0,366.000000,713.000000,86.000000
IMO,1458,178,0,396.000000,655.000000,229.000000
AUP,719,225,0,61.000000,406.000000,27.000000
IND,550,240,0,94.000000,192.000000,24.000000

In [94]:
pd.read_csv("2022_results_3pp.csv").groupby("PartyAb").sum()
# ["first"] / pd.read_csv("2022_results_3pp_pc.csv").groupby("PartyAb").sum()["first"].sum()

         btl  first    ALP     LP    GRN  exhausted
PartyAb
AJP        2   1892    473    305    946        168
ALP        2  95232  95119     29     76          8
AUP        2    719    221     93    375         30
DAVI       2  60304  28607  10010  20435       1252
GRN        2  29379     66      5  29307          1
HMP        2   4550   1319   1003   1774        454
IMO        2   1458    212    486    316        444
IND        1    550    266    106    153         25
KCBR       2  12613   5209   1565   5618        221
LP         2  70745    213  70433     67         32
SPP        2   1631    499    421    592        119
UAPP       2   6144   1003   3535    688        918

In [ ]:
ps.read_csv("")